export const CONNECT_TO_CHAT_SUCCESS = 'CONNECT_TO_CHAT_SUCCESS';
export const CONNECT_TO_CHAT_FAIL = 'CONNECT_TO_CHAT_FAIL';

export const LOGIN_TO_TOPIC_SUCCESS = 'LOGIN_TO_TOPIC_SUCCESS';
export const LOGIN_TO_TOPIC_FAIL = 'LOGIN_TO_TOPIC_FAIL';

export const LOGOUT_FROM_TOPIC_SUCCESS = 'LOGOUT_FROM_TOPIC_SUCCESS';
export const LOGOUT_FROM_TOPIC_FAIL = 'LOGOUT_FROM_TOPIC_FAIL';

export const CHAT_TEXT_RECEIVED_SUCCESS = 'CHAT_TEXT_RECEIVED_SUCCESS';
export const CHAT_TEXT_RECEIVED_FAILED = 'CHAT_TEXT_RECEIVED_FAILED';

export const CHAT_USER_JOINED = 'CHAT_USER_JOINED';
export const CHAT_USER_LEFT = 'CHAT_USER_LEFT';
export const CHAT_INFO_RECEIVED_FAILED = 'CHAT_INFO_RECEIVED_FAILED';

export const CHAT_MSG_EMITTED_SUCCESS = 'CHAT_MSG_EMITTED_SUCCESS';
export const CHAT_MSG_EMITTED_FAIL = 'CHAT_MSG_EMITTED_FAIL';

export const CHAT_USERS_LOADED_SUCCESS = 'CHAT_USERS_LOADED_SUCCESS';
export const CHAT_USERS_LOADED_FAIL = 'CHAT_USERS_LOADED_FAIL';

export const CHAT_TOPICS_LOADED_SUCCESS = 'CHAT_TOPICS_LOADED_SUCCESS';
export const CHAT_TOPICS_LOADED_FAIL = 'CHAT_TOPICS_LOADED_FAIL';
